name: Build Seatbelt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 3.5
      run: |
        echo Installing .NET Framework 3.5
        dism /online /enable-feature /featurename:NetFx3 /all

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Test
      run: |
        echo No tests configured
        # If you have tests, add the command to run them here
