name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  linux-windows-build:
    name: CSharp Build
    runs-on: windows-latest
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Check out code
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: MSBuild
      run: |
        msbuild.exe Seatbelt.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=compiled/
        dir Seatbelt/compiled
    - name: update release file
      run: | 
        echo Seatbelt.exe > Release.txt
        echo Seatbelt.exe.config > Release.txt

    - name: Test
      run: cat Release.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: Release.txt
